name: Run unit tests

on:
  push:

jobs:

  run-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests with Gradle
        run: ./gradlew clean test
